spring:
  redis:
    port: 6379
    #    password: 123456
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 1000 # 连接池大连接数（使用负值表示没有限制）
        max-idle: 1000 # 连接池中的大空闲连接
        min-idle: 10 # 连接池中的小空闲连接
        max-wait: 1000 # 连接池大阻塞等待时间（使用负值表示没有限制）
        shutdown-timeout: 100   # 关闭超时时间
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bottle_pay?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 50
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 30000
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  reids:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 6000
        max-wait: 1000
        max-idle: 400

